Repository milieuinfo/webcomponent-vl-ui-search-filter, pull requests merged in 2020-03, with the labels that each got.

#12 E2E tests voor search-filter
  demo/vl-search-filter.html
  test/e2e/components/vl-search-filter.js
  test/e2e/pages/vl-search-filter.page.js
  test/e2e/search-filter.test.js
Labels: chore

#13 Update vl-ui-util
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: chore, maintenance

#14 API uitbreiding om form data op te vragen
  src/vl-search-filter.js
  test/unit/vl-search-filter.test.html
Labels: enhancement

#16 Update vl-ui-core
  package-lock.json
  package.json
Labels: chore

#17 Update vl-ui-core
  package-lock.json
  package.json
Labels: chore
